### ISSUE TITLE
My image isn't appearing

### ISSUE THREAD

**Issue by murraycollingwood** [pontedilana/php-weasyprint#9]
Hello

Initially I was thinking this might be a WeasyPrint issue, but the command line version is working correctly.
Here are a couple of real URLs as examples you can play with.

First a real image that will work:
`https://sobs.com.au/docs/pix/simple-example.png`

Second, a secure image retrieval that doesn't produce any image (but it does work when using WeasyPrint from the command line):
`https://sobs.com.au/ui/fap.php?fap=WyJub3RpY2VBdHRhY2htZW50Iiw3NjI5MjksIi4uXC91cGxvYWRzXC8xNVwvbm90aWNlc1wvMjAyM1wvMDVcLzc2MjkyOV8xNjg0MTQwOTE5XzEuanBnIl0` 

Cheers
Murray

**Comment by murraycollingwood** [comment]
Anybody?

**Comment by endelwar** [comment]
Hi @murraycollingwood, sorry for the delay, working issues have arisen.

Is this image used in an html file? How? Whis is the command line generated by php-weasyprint?

I need some debug info to help you.
